"""initial_schema

Revision ID: 3f58847efce0
Revises: 
Create Date: 2026-05-12 08:41:08.507686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.db_models


# revision identifiers, used by Alembic.
revision: str = '3f58847efce0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.models.db_models.GUID(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('projects',
    sa.Column('id', app.models.db_models.GUID(length=32), nullable=False),
    sa.Column('user_id', app.models.db_models.GUID(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('business_idea', sa.Text(), nullable=False),
    sa.Column('target_market', sa.String(length=255), nullable=True),
    sa.Column('budget_range', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'running', 'completed', 'error')", name='ck_projects_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_share_token'), ['share_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_projects_user_status', ['user_id', 'status'], unique=False)

    op.create_table('project_reports',
    sa.Column('id', app.models.db_models.GUID(length=32), nullable=False),
    sa.Column('project_id', app.models.db_models.GUID(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_reports', schema=None) as batch_op:
        batch_op.create_index('ix_project_reports_project_generated', ['project_id', 'generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_reports_project_id'), ['project_id'], unique=False)

    op.create_table('workflow_runs',
    sa.Column('id', app.models.db_models.GUID(length=32), nullable=False),
    sa.Column('project_id', app.models.db_models.GUID(length=32), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'failed')", name='ck_workflow_runs_status'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_runs_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_workflow_runs_project_status', ['project_id', 'status'], unique=False)

    op.create_table('agent_messages',
    sa.Column('id', app.models.db_models.GUID(length=32), nullable=False),
    sa.Column('workflow_id', app.models.db_models.GUID(length=32), nullable=False),
    sa.Column('sender', sa.String(length=100), nullable=False),
    sa.Column('recipient', sa.String(length=100), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.create_index('ix_agent_messages_workflow_created', ['workflow_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('agent_tasks',
    sa.Column('id', app.models.db_models.GUID(length=32), nullable=False),
    sa.Column('workflow_id', app.models.db_models.GUID(length=32), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('input_context', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('execution_time', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')", name='ck_agent_tasks_status'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_tasks_workflow_id'), ['workflow_id'], unique=False)
        batch_op.create_index('ix_agent_tasks_workflow_started', ['workflow_id', 'started_at'], unique=False)
        batch_op.create_index('ix_agent_tasks_workflow_status', ['workflow_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_tasks_workflow_status')
        batch_op.drop_index('ix_agent_tasks_workflow_started')
        batch_op.drop_index(batch_op.f('ix_agent_tasks_workflow_id'))

    op.drop_table('agent_tasks')
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_messages_workflow_id'))
        batch_op.drop_index('ix_agent_messages_workflow_created')

    op.drop_table('agent_messages')
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_workflow_runs_project_status')
        batch_op.drop_index(batch_op.f('ix_workflow_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_is_deleted'))

    op.drop_table('workflow_runs')
    with op.batch_alter_table('project_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_reports_project_id'))
        batch_op.drop_index('ix_project_reports_project_generated')

    op.drop_table('project_reports')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_user_status')
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))
        batch_op.drop_index(batch_op.f('ix_projects_share_token'))
        batch_op.drop_index(batch_op.f('ix_projects_is_deleted'))

    op.drop_table('projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
